//
//  CommonImg.h
//  CAMELLIAE
//
//  Created by 张越 on 16/3/17.
//  Copyright © 2016年 张越. All rights reserved.
//

#ifndef CommonImg_h
#define CommonImg_h

#define KServeLightImg               @"HomeServeLight.png"
#define KServeDarkImg                @"HomeServeDark.png"
#define KVIPLightImg                 @"HomeVIPLight.png"
#define KVIPDarkImg                  @"HomeVIPDark.png"
#define KExerciseAndConsultLightImg  @"HomeNewsLight.png"
#define KExerciseAndConsultDarkImg   @"HomeNewsDark.png"
#define KTabBarBgImg                 @"bottomView.png"
#define KLOGOImg                     @"LOGO.png"
#define KNavcImg                     @"navc.png"
#define KPersonalImg                 @"personal.png"
#define KPlaceImg                    @"place.png"
#define KActivityPlaceholderImg      @"activityPlaceholderImage"
#define KNewsPlaceholderImg          @"newsPlaceholderImage"
#define KVIPBlackPigmentImg          @"blackPigment.png"
#define KBlackImg                    @"black.png"
#define KGoldImg                     @"gold.png"
#define KPinkImg                     @"pink.png"
#define KActivityCollectImg          @"personalfavourite.png"
#define KMessageImg                  @"personalMes.png"
#define KPersonInfoImg               @"personInfo.png"
#define KPointsImg                   @"Three-Coin-stacks.png"
#define KReserveImg                  @"appointment.png"
#define KSettingImg                  @"Setting-tool.png"
#define KUserHeadImg                 @"userHead.png"
#define KFashionImg                  @"serveLife.png"
#define KGrowupImg                   @"growup.png"
#define KTravelImg                   @"travel.png"
#define KVIPGoldImg                  @"goldMember.png"
#define KVIPLnkImg                   @"lnkMember.png"
#define KVIPPinkImg                  @"pinkMember.png"
#define KVIPPurpleImg                @"purpleMember.png"
#define KMoreNewsImg                 @"moretings.png"
#define KFashionBGImg                @"fashionBackground.png"
#define KGrowupBGImg                 @"growupBackground.png"
#define KTravelBGImg                 @"travelBackground.png"
#define KVIPGoldBGImg                @"newGoldMember.png"
#define KVIPLnkBGImg                 @"newLnkMember.png"
#define KVIPPinBGkImg                @"newPinkMember.png"
#define KVIPPurpleBGImg              @"newPurpleMember.png"
#define KCloseVCImg                  @"closeButton.png"
#define KVIPDetailCamelliaImg        @"VIPCamellia.png"
#define KVIPDetailPinkImg            @"VIPDetailpink.png"
#define KVIPDetailStageImg           @"VIPDetailStage.png"
#define KVIPLOGOImg                  @"VIPLOGO.png"
#define KVIPUpgradeImg               @"VIPUpgrade.png"
#define KVIPDetailPurpleImg          @"purple.png"
#define KVIPDetailGoldImg            @"VIPGlod.png"
#define KVIPDetailGoldLOGOImg        @"LOGOOfGold.png"
#define KVIPDetailLnkImg             @"VIPDetailLnkBackground.png"
#define KVIPDetailLnkLOGOImg         @"LOGOOfLnk.png"
#define BlackBackBtnImg              @"blackBack.png"
#define WhiteBackBtnImg              @"whiteBackBtn.png"
#define BlackBackBtnOfRowImg         @"BackBtnOfRow"
#define KEnterPersonVCImg            @"enterPerson.png"
#define KLoginVCBackGroundImg        @"loginBackground.png"
#define KLoginVCLoginLOGOImg         @"loginLOGO.png"
#define KLoginVCOfRegisterBtnImg     @"loginOfRegisterBtn.png" 
#define KLoginVCOfLoginBtnImg        @"loginOfLoginBtn.png"
#define KLoginInputFrameImg          @"form.png"
#define SendVerificationCodeBtnImg   @"verificationCodeButton.png"
#define KLoginBGImg                  @"loginBGImage.png"
#define KLoginTwoBGImg               @"loadingTwo.png"
#define KNextBtnImg                  @"nextBtn.png"
#define KFinshedBtnImg               @"finshedBtn.png"
#define KGirlBtnImg                  @"girlBtn.png"
#define KBoyBtnImg                   @"boyBtn.png"
#define KEnterAppImg                 @"loadingBGImage.png"
#define KExpiredImg                  @"expired.png"
#define KNotExpiredImg               @"notExpired.png"
#define KNotDataImg                  @"notData.png"
#define KCollectBtnImg               @"collect.png"
#define KCollectedBtnImg             @"collected.png"
#define KFeedbackImg                 @"feedback.png"
#define KActivityDetailTimeImg       @"history.png"
#define KActivityDetailAddressImg    @"location.png"
#define KActivityNumImg              @"call.png"
#define KActivityMemberImg           @"friends.png"
#define KActivityVIPImg              @"detaileVIP.png"
#define KMoreActionImg               @"more.png"
#define KNotDataBackgroundImg        @"noDataBackground.png"
#define KShareToConverImg            @"shareOfConver.png"
#define KShareToCircleImg            @"shareOfCircle.png"
#define KShareToweiboImg             @"weibo.png"
#define KWhiteShareImg               @"whiteShare.png"
#define KBlackShareImg               @"share.png"
#define KShareToDouBImg              @"doub.png"
#define KShareToEmailImg             @"Email.png"

#define KOlympicImg                  @"Olympic.png"
#define KGaNaImg                     @"gana.jpg"
#define KHealthyImg                  @"healthy.jpg"          
#endif /* CommonImg_h */
